package flights

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"net/url"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/network"
	"github.com/chromedp/chromedp"
)

// BrowserSession is a [Session] that routes flight searches through a headless
// Chrome/Chromium browser instead of calling the Google Flights RPC endpoints
// directly. Google requires a BotGuard attestation token
// (X-Goog-BatchExecute-Bgr header) on GetShoppingResults/GetCalendarGraph
// requests, which is generated by browser-side JS and signs the exact request
// payload — so direct HTTP replication no longer works. BrowserSession loads
// the real search page and captures the RPC responses the page's own JS makes.
//
// The browser is launched once and reused; each search opens a fresh tab.
// Close must be called to shut the browser down.
type BrowserSession struct {
	*Session

	// Timeout bounds a single search (page load + RPC capture). Default 90s.
	Timeout time.Duration

	allocCancel   context.CancelFunc
	browserCtx    context.Context
	browserCancel context.CancelFunc
}

// NewBrowserSession creates a Session and starts a headless browser next to
// it. The browser binary is auto-detected (Chrome, then Chromium); set the
// CHROME_BIN environment variable to override.
func NewBrowserSession() (*BrowserSession, error) {
	session, err := New()
	if err != nil {
		return nil, err
	}

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.NoSandbox,
		chromedp.Flag("disable-dev-shm-usage", true),
	)
	if bin := os.Getenv("CHROME_BIN"); bin != "" {
		opts = append(opts, chromedp.ExecPath(bin))
	}

	allocCtx, allocCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	browserCtx, browserCancel := chromedp.NewContext(allocCtx)

	// Start the browser now so a broken/missing binary fails fast.
	if err := chromedp.Run(browserCtx); err != nil {
		browserCancel()
		allocCancel()
		return nil, fmt.Errorf("could not start browser: %w", err)
	}

	return &BrowserSession{
		Session:       session,
		Timeout:       90 * time.Second,
		allocCancel:   allocCancel,
		browserCtx:    browserCtx,
		browserCancel: browserCancel,
	}, nil
}

// Close shuts down the browser.
func (bs *BrowserSession) Close() {
	bs.browserCancel()
	bs.allocCancel()
}

func setConsentCookies() chromedp.ActionFunc {
	return func(ctx context.Context) error {
		expires := cdp.TimeSinceEpoch(time.Now().Add(365 * 24 * time.Hour))
		for _, c := range [][2]string{
			{"SOCS", "CAESEwgDEgk0ODE3Nzk3MjQaAmVuIAEaBgiA_LyaBg"},
			{"CONSENT", "YES+cb.20210720-07-p0.en+FX+410"},
		} {
			err := network.SetCookie(c[0], c[1]).
				WithDomain(".google.com").
				WithPath("/").
				WithExpires(&expires).
				Do(ctx)
			if err != nil {
				return err
			}
		}
		return nil
	}
}

// rpcTab is a browser tab that records the response of every request whose
// URL matches. Finished responses are announced on ids in arrival order;
// bodies are fetched with next().
type rpcTab struct {
	ctx    context.Context
	cancel context.CancelFunc
	ids    chan network.RequestID
}

// flightsRPC matches a FlightsFrontendService RPC by name.
func flightsRPC(rpcName string) func(string) bool {
	return func(url string) bool {
		return strings.Contains(url, "FlightsFrontendService/"+rpcName)
	}
}

// travelBatchRPC matches a TravelFrontendUi batchexecute call carrying the
// given rpcid (used by Google Hotels).
func travelBatchRPC(rpcid string) func(string) bool {
	return func(url string) bool {
		return strings.Contains(url, "TravelFrontendUi/data/batchexecute") &&
			strings.Contains(url, "rpcids="+rpcid)
	}
}

func (bs *BrowserSession) newRPCTab(ctx context.Context, match func(url string) bool) *rpcTab {
	tabCtx, cancelTab := chromedp.NewContext(bs.browserCtx)

	timeout := bs.Timeout
	if timeout <= 0 {
		timeout = 90 * time.Second
	}
	tabCtx, cancelTimeout := context.WithTimeout(tabCtx, timeout)

	// Cancel the tab if the caller's context ends first.
	stopAfter := context.AfterFunc(ctx, cancelTab)

	tab := &rpcTab{
		ctx: tabCtx,
		cancel: func() {
			stopAfter()
			cancelTimeout()
			cancelTab()
		},
		ids: make(chan network.RequestID, 16),
	}

	var mu sync.Mutex
	matched := map[network.RequestID]bool{}

	chromedp.ListenTarget(tabCtx, func(ev interface{}) {
		switch e := ev.(type) {
		case *network.EventResponseReceived:
			if match(e.Response.URL) {
				mu.Lock()
				matched[e.RequestID] = true
				mu.Unlock()
			}
		case *network.EventLoadingFinished:
			mu.Lock()
			ok := matched[e.RequestID]
			mu.Unlock()
			if ok {
				select {
				case tab.ids <- e.RequestID:
				default:
				}
			}
		}
	})

	return tab
}

// next waits for the next finished RPC response and returns its body.
// waitTimeout bounds only this wait; the tab's own deadline still applies.
func (t *rpcTab) next(waitTimeout time.Duration) ([]byte, error) {
	var id network.RequestID
	select {
	case id = <-t.ids:
	case <-time.After(waitTimeout):
		return nil, fmt.Errorf("no RPC response within %s", waitTimeout)
	case <-t.ctx.Done():
		return nil, fmt.Errorf("tab closed while waiting for RPC response: %w", t.ctx.Err())
	}

	var body []byte
	err := chromedp.Run(t.ctx, chromedp.ActionFunc(func(ctx context.Context) error {
		var err error
		body, err = network.GetResponseBody(id).Do(ctx)
		return err
	}))
	if err != nil {
		return nil, fmt.Errorf("could not read RPC response body: %w", err)
	}
	return body, nil
}

// GetOffers works like [Session.GetOffers] but performs the search through the
// headless browser. See [Session.GetOffers] for the returned values.
func (bs *BrowserSession) GetOffers(ctx context.Context, args Args) ([]FullOffer, *PriceRange, error) {
	if err := args.ValidateOffersArgs(); err != nil {
		return nil, nil, err
	}

	searchURL, err := bs.Session.SerializeURL(ctx, args)
	if err != nil {
		return nil, nil, err
	}

	tab := bs.newRPCTab(ctx, flightsRPC("GetShoppingResults"))
	defer tab.cancel()

	if err := chromedp.Run(tab.ctx,
		network.Enable(),
		setConsentCookies(),
		chromedp.Navigate(searchURL),
	); err != nil {
		return nil, nil, fmt.Errorf("browser navigation failed: %w", err)
	}

	body, err := tab.next(bs.Timeout)
	if err != nil {
		return nil, nil, fmt.Errorf("waiting for GetShoppingResults: %w", err)
	}

	offers, priceRange := parseShoppingResults(bytes.NewReader(body), args.ReturnDate)
	return offers, priceRange, nil
}

// clickButton clicks the first enabled button-like element whose aria-label or
// text equals label (case-insensitive). Returns whether an element was clicked.
func clickButton(ctx context.Context, label string) (bool, error) {
	expr := fmt.Sprintf(`(() => {
		const want = %q.toLowerCase();
		const els = [...document.querySelectorAll('button,[role="tab"],[role="button"]')];
		const hit = els.find(e =>
			((e.getAttribute('aria-label')||'').trim().toLowerCase() === want ||
			 (e.textContent||'').trim().toLowerCase() === want) && !e.disabled);
		if (hit) { hit.click(); return true; }
		return false;
	})()`, label)
	var clicked bool
	err := chromedp.Run(ctx, chromedp.Evaluate(expr, &clicked))
	return clicked, err
}

// clickButtonRetry polls for the button until it can be clicked or the timeout
// elapses.
func clickButtonRetry(ctx context.Context, label string, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for {
		clicked, err := clickButton(ctx, label)
		if err != nil {
			return err
		}
		if clicked {
			return nil
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("%q button not found", label)
		}
		select {
		case <-time.After(500 * time.Millisecond):
		case <-ctx.Done():
			return ctx.Err()
		}
	}
}

// forceEnglishUI rewrites the hl query parameter to English so that the
// UI elements GetPriceGraph clicks by label have known names.
func forceEnglishUI(searchURL string) string {
	u, err := url.Parse(searchURL)
	if err != nil {
		return searchURL
	}
	q := u.Query()
	q.Set("hl", "en")
	u.RawQuery = q.Encode()
	return u.String()
}

// GetPriceGraph works like [Session.GetPriceGraph] but performs the search
// through the headless browser: it opens the search page, opens the "Price
// graph" view, and pages through it ("Scroll forward") until the requested
// date range is covered.
func (bs *BrowserSession) GetPriceGraph(ctx context.Context, args PriceGraphArgs) ([]Offer, error) {
	if err := args.Validate(); err != nil {
		return nil, err
	}

	searchURL, err := bs.Session.SerializeURL(ctx, args.Convert())
	if err != nil {
		return nil, err
	}
	// The buttons are clicked by their English labels, so force the UI
	// language; prices still follow args.Currency.
	searchURL = forceEnglishUI(searchURL)

	tab := bs.newRPCTab(ctx, flightsRPC("GetCalendarGraph"))
	defer tab.cancel()

	if err := chromedp.Run(tab.ctx,
		network.Enable(),
		setConsentCookies(),
		chromedp.Navigate(searchURL),
	); err != nil {
		return nil, fmt.Errorf("browser navigation failed: %w", err)
	}

	// Open the price graph view. The button can exist in the DOM before the
	// page is ready to act on the click, so re-click until the first
	// GetCalendarGraph response actually arrives.
	var firstBody []byte
	for {
		if err := clickButtonRetry(tab.ctx, "Price graph", 15*time.Second); err != nil {
			return nil, err
		}
		var err error
		if firstBody, err = tab.next(15 * time.Second); err == nil {
			break
		}
		if tab.ctx.Err() != nil {
			return nil, fmt.Errorf("waiting for GetCalendarGraph: %w", tab.ctx.Err())
		}
	}

	byDate := map[time.Time]Offer{}
	var maxDate time.Time

	// The first window covers roughly [start-7d, start+31d]; every "Scroll
	// forward" click adds ~13 days. The range is capped at 161 days by
	// Validate, so bound the number of clicks defensively.
	body := firstBody
	for click := 0; click < 25; click++ {
		if click > 0 {
			var err error
			if body, err = tab.next(20 * time.Second); err != nil {
				break // return what has been collected so far
			}
		}

		for _, o := range parsePriceGraphResults(bytes.NewReader(body)) {
			byDate[o.StartDate] = o
			if o.StartDate.After(maxDate) {
				maxDate = o.StartDate
			}
		}

		if !maxDate.Before(args.RangeEndDate) {
			break
		}
		clicked, err := clickButton(tab.ctx, "Scroll forward")
		if err != nil || !clicked {
			break
		}
	}

	offers := make([]Offer, 0, len(byDate))
	for _, o := range byDate {
		if o.StartDate.Before(args.RangeStartDate) || o.StartDate.After(args.RangeEndDate) {
			continue
		}
		offers = append(offers, o)
	}
	sortSlice(offers, func(lv, rv Offer) bool {
		return lv.StartDate.Before(rv.StartDate)
	})
	return offers, nil
}

// protoVarint encodes n as a protobuf varint.
func protoVarint(n int) []byte {
	out := []byte{}
	for {
		b := byte(n & 0x7f)
		n >>= 7
		if n != 0 {
			out = append(out, b|0x80)
		} else {
			return append(out, b)
		}
	}
}

// protoField encodes a length-delimited protobuf field.
func protoField(num int, payload []byte) []byte {
	out := append([]byte{}, byte(num<<3|2))
	out = append(out, protoVarint(len(payload))...)
	return append(out, payload...)
}

// hotelTS encodes the stay dates and currency into the `ts` protobuf URL
// parameter. Google's /travel/search page ignores the legacy checkin/checkout
// and curr query parameters — without a ts carrying the dates the page prices
// a default one-night stay. Layout (reverse-engineered from the URLs the page
// itself produces): dates at field 3.2.2 as {1: checkin{y,m,d}, 2:
// checkout{y,m,d}, 3: nights}, currency string at field 5.1.7.
func hotelTS(checkIn, checkOut time.Time, currencyCode string) string {
	dateMsg := func(t time.Time) []byte {
		out := append([]byte{0x08}, protoVarint(t.Year())...)
		out = append(out, 0x10)
		out = append(out, protoVarint(int(t.Month()))...)
		out = append(out, 0x18)
		out = append(out, protoVarint(t.Day())...)
		return out
	}
	nights := int(checkOut.Sub(checkIn).Hours() / 24)
	stay := protoField(1, dateMsg(checkIn))
	stay = append(stay, protoField(2, dateMsg(checkOut))...)
	stay = append(stay, 0x18)
	stay = append(stay, protoVarint(nights)...)
	f3 := protoField(3, protoField(2, protoField(2, stay)))

	curr := protoField(7, []byte(currencyCode))
	f5 := protoField(5, append(protoField(1, curr), protoField(3, nil)...))

	return base64.RawURLEncoding.EncodeToString(append(f3, f5...))
}

// hotelSearchURL builds the Google Hotels search page URL for the given stay.
func hotelSearchURL(args HotelArgs) string {
	q := url.Values{}
	q.Set("q", "hotels in "+args.Location)
	q.Set("ts", hotelTS(args.CheckInDate, args.CheckOutDate, args.currencyCode()))
	if !args.Lang.IsRoot() {
		q.Set("hl", args.Lang.String())
	}
	return "https://www.google.com/travel/search?" + q.Encode()
}

// GetHotelOffers works like [Session.GetHotelOffers] but performs the search
// through the headless browser: it loads the Google Hotels search page and
// captures the AtySUc listing RPC the page makes, which carries the live
// date-specific prices (the direct RPC returns hotels without prices since
// Google started requiring BotGuard attestation).
func (bs *BrowserSession) GetHotelOffers(ctx context.Context, args HotelArgs) ([]Hotel, error) {
	if err := args.Validate(); err != nil {
		return nil, err
	}

	tab := bs.newRPCTab(ctx, travelBatchRPC("AtySUc"))
	defer tab.cancel()

	if err := chromedp.Run(tab.ctx,
		network.Enable(),
		setConsentCookies(),
		chromedp.Navigate(hotelSearchURL(args)),
	); err != nil {
		return nil, fmt.Errorf("browser navigation failed: %w", err)
	}

	body, err := tab.next(bs.Timeout)
	if err != nil {
		return nil, fmt.Errorf("waiting for AtySUc: %w", err)
	}

	return parseHotelOffers(bytes.NewReader(body), args)
}

// GetHotelPriceGraph works like [Session.GetHotelPriceGraph] but performs each
// sampled search through the headless browser (one page load per sampled
// check-in date).
func (bs *BrowserSession) GetHotelPriceGraph(ctx context.Context, args HotelPriceGraphArgs) ([]HotelDateOffer, error) {
	if err := args.Validate(); err != nil {
		return nil, err
	}

	var offers []HotelDateOffer
	for ci := args.RangeStartDate; !ci.After(args.RangeEndDate); ci = ci.AddDate(0, 0, args.StepDays) {
		co := ci.AddDate(0, 0, args.Nights)

		hotels, err := bs.GetHotelOffers(ctx, HotelArgs{
			Location:     args.Location,
			CheckInDate:  ci,
			CheckOutDate: co,
			HotelOptions: args.HotelOptions,
		})
		if err != nil {
			return nil, fmt.Errorf("hotel offers for %s: %v", ci.Format("2006-01-02"), err)
		}

		cheapest, ok := cheapestPriced(hotels)
		if !ok {
			continue
		}
		offers = append(offers, HotelDateOffer{
			CheckInDate:  ci,
			CheckOutDate: co,
			Hotel:        cheapest,
		})
	}
	return offers, nil
}
